use LD instead of CC in direct library test
The libraries are needed at link time, so thise makes more sense.
It also avoids problems we have because of it failing to resolve
some symbols when looking for -l libraries.

Example from subversion build:

    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_hv_iterinit'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_mg_get'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_av_len'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_get_sv'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_newRV_noinc'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_sv_2bool_flags'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_sv_2mortal'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_hv_iternextsv'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_free_tmps'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `PL_stack_sp'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_PerlIO_read'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_looks_like_number'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `PL_markstack_max'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_sv_setref_pv'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `PL_markstack_ptr'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_PerlIO_close'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_pop_scope'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_call_sv'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_sv_free2'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `PL_sv_undef'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_stack_grow'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_sv_newmortal'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_av_fetch'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_call_method'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_PerlIO_fileno'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `PL_tmps_floor'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_save_strlen'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_sv_2io'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_newSViv'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_hv_common_key_len'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_mg_find'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_sv_isobject'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_PerlIO_write'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_newSVpv'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_av_push'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_sv_2iv_flags'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `PL_tmps_ix'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `PL_stack_max'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_croak'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_push_scope'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_newSV_type'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `svn_swig_pl_get_current_pool'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_sv_derived_from'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_newSVpvn'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_markstack_grow'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `PL_stack_base'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_newRV'
    subversion/bindings/swig/perl/libsvn_swig_perl/.libs/libsvn_swig_perl-1.so: undefined reference to `Perl_sv_2pv_flags'
    collect2: error: ld returned 1 exit status
    Warning (mostly harmless): No library found for -lsvn_swig_perl-1

Thie may be related to us using a shared library for libperl.

If we use `ld` and `lddlflags`, we can avoid this because we
will build a shared library and only need the symbols at runtime.
This still notices if the library is missing, as can be evidenced
by

    # x86_64-pc-linux-gnu-gcc --shared try_mm.c -lnotfound
    /usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld: cannot find -lnotfound
    collect2: error: ld returned 1 exit status

it might be better to use `CC -c` + `LD`, but this is simpler and
perl needs `LD=gcc` instead of `LD=ld` anyway to build.